server {
    listen 80;
    server_name api6.grwxtech.com;
    index index.php index.html;

    error_log /var/log/nginx/auth_error.log;
    access_log /var/log/nginx/auth_access.log;

    root /var/www/public;

    client_max_body_size 1G;

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ ^/.+\.php(/|$) {
        fastcgi_pass app_api6:9000;
        include fastcgi_params;
        fastcgi_read_timeout 600;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
